name: comment-link-close-issue

on:
  issues:
    types: [opened]

jobs:
  comment_on_issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'The shortened link is https://vchrombie.github.io/links/${{ github.event.issue.number }}'
          })
          github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Stale']
            })
    - uses: actions/stale@v5
      with:
        days-before-issue-close: 0
        repo-token: ${{ secrets.GITHUB_TOKEN }}
